// Code generated by Slice Machine. DO NOT EDIT.

import Content from './Content';
import Hero from './Hero';

export {
	Content,
	Hero,
};

export const components = {
	content: Content,
	hero: Hero,
};
